{
  "settings": {
    "react": {
      "version": "detect"
    }
  },
  "env": {
    "browser": true,
    "es2021": true
  },
  "extends": [
    "eslint:recommended",
    "plugin:react/recommended",
  ],
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": 12,
    "sourceType": "module"
  },
  "plugins": [
    "react",
    "react-hooks"
  ],
  "rules": {
    react/prop-types: 0,
    react/jsx-uses-react: 0,
    react/react-in-jsx-scope: 0,
    eslint-disable-next-line: 0,
    no-unused-vars: 0,
    react-hooks/exhaustive-deps: 1
  }
}
