{
  "settings": {
    "react": {
      "version": "detect"
    },
    "import/resolver": {
      "node": {
        "extensions": [ ".js", ".jsx" ],
        "moduleDirectory": [ "src", "node_modules" ]
      }
    }
  },
  "env": {
    "browser": true,
    "es2021": true
  },
  "extends": [
    "airbnb",
    "eslint:recommended",
    "plugin:react/recommended"
  ],
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": 12,
    "sourceType": "module"
  },
  "plugins": [
      "react"
  ],
  "rules": {
    semi: [2, "always"],
    react/prop-types: 0,
    react/jsx-uses-react: 0,
    eslint-disable-next-line: 0,
  }
}
