{
  "settings": {
    "react": {
      "version": "detect"
    }
  },
  "env": {
    "browser": true,
    "es2021": true
  },
  "extends": [
      "eslint:recommended",
      "plugin:react/recommended"
  ],
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": 12,
    "sourceType": "module"
  },
  "plugins": [
      "react"
  ],
  "rules": {
    react/prop-types: 0,
    react/jsx-uses-react: 0,
    react/react-in-jsx-scope: 0,
    eslint-disable-next-line: 0,
    quotes: [2, "single", { "avoidEscape": true }],
    jsx-quotes: [2, "prefer-single"]
  }
}
